// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://douhbaztorwgzojwmtmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvdWhiYXp0b3J3Z3pvandtdG11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjA5NDQsImV4cCI6MjA2NDUzNjk0NH0.tlas9ReicwE_tdYMtlJmzb0Iw6mB-MKYt-C2oKBNufg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);